### ISSUE TITLE
Is the output of SPAligner in this format ?

### ISSUE THREAD

**Issue by RolandFaure** [ocxtal/gpa#1]
Hi,

I am looking with interest to SPAligner. My question is: is the GPA format, as described here, still the output of SPAligner ? Using SPAligner, it looks like there are some divergences with this format. For example, the field bname:Z is composed in my file of the name of the contig in the GFA and then, directly appended, + or - (which I guess is the orientation that should be in the field adir:A). The field adir:A  is always set to '+'.

Thanks in advance,

Roland

**Comment by ocxtal** [comment]
my answer is: this repository has nothing to do with the SPAligner. see the reference of the tool instead. thanks,

**Comment by RolandFaure** [comment]
Thank you, sorry I did not realise that (since this repo is cited from the page of SPAligner)
